### ISSUE TITLE
Intake Current Counting

### ISSUE THREAD

**Issue by maniyar1** [frc3324/Metrobots2020Robot#1]
1. Read current from TalonSRX 
2. Send current over to PC via SmartDashboard
3. Figure out if you can count balls via current

**Comment by maniyar1** [comment]
https://phoenix-documentation.readthedocs.io/en/latest/ - TalonSRX
https://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.html - Smartdashboard

**Comment by MoormanA** [comment]
I BLESS THE RAINS DOWN IN AFRICA

**Comment by MoormanA** [comment]
ITS GONNA TAKE SOME TIME TO DO THE THINGS WE NEVER HAD

**Comment by MoormanA** [comment]
HE TURNED TO ME AS IF TO SAY
